### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'split'

### ISSUE THREAD

**Issue by pronoym99** [r3nt0n/bopscrk#22] opened 2023-02-11 08:26 UTC
Seems similar to #18 but I don't understand how to resolve the same. I have separately printed out `self.read_config('TRANSFORMS', 'leet_charset')` which comes out as `False`. Any idea to get around the same?

Following is the error traceback.

```
Traceback (most recent call last):
  File "C:\Users\Microsoft\AppData\Local\Programs\Python\Python310\Scripts\bopscrk-script.py", line 33, in <module>
    sys.exit(load_entry_point('bopscrk==2.4.5', 'console_scripts', 'bopscrk')())
  File "C:\Users\Microsoft\AppData\Local\Programs\Python\Python310\lib\site-packages\bopscrk-2.4.5-py3.10.egg\bopscrk\bopscrk.py", line 22, in start
    main.run(name, __version__)
  File "C:\Users\Microsoft\AppData\Local\Programs\Python\Python310\lib\site-packages\bopscrk-2.4.5-py3.10.egg\bopscrk\modules\main.py", line 46, in run
    Config.setup()
  File "C:\Users\Microsoft\AppData\Local\Programs\Python\Python310\lib\site-packages\bopscrk-2.4.5-py3.10.egg\bopscrk\modules\config.py", line 49, in setup
    self.LEET_CHARSET = (self.read_config('TRANSFORMS', 'leet_charset')).split()
AttributeError: 'bool' object has no attribute 'split'
```

**Comment by r3nt0n** [comment] 2023-02-11 13:13
Hello! :)

I am not able to reproduce the issue, please provide some details:

+ Did you install it via pip?
+ Have you made any changes to the config file (`bopscrk.cfg`)?
+ What arguments are you passing to execute the script? (if it was in interactive mode, what was the input for each option?)

If you think of anything else that can help me reproduce the issue, please let me know.

Thank you for the feedback!

**Comment by pronoym99** [comment] 2023-02-11 14:27
Hi!

- Yes, I have installed it via pip
- Yes I have made changes in `bopscrk.cfg`. Following is an exact copy of the same after stripping the initial introduction :

```
[GENERAL]
# Number of threads to use in multithreaded operations
threads=32

[COMBINATIONS]
# Enables extra combination and additions at begining and end of words
# example: (john, doe) => 123john, john123, 123doe, doe123, john123doe doe123john
extra_combinations=true
# SEPARATORS CHARSET - Characters to use in extra-combinations
separators_chars=._-$%%&#@
separators_strings=123 xXx !!
# Uncomment the following line to get an extensive charset for separators
separators_chars=!"#$%%&'()*+,-./:;<=>?@[\]^_`{|}~

[TRANSFORMS]
# LEET REPLACEMENT CHARSET
# characters to replace and correspondent substitute in leet transforms
leet_charset=a:4 e:3 i:1 o:0 s:$
# Uncomment the following line to get an extensive charset
leet_charset=a:4 a:@ e:3 i:1 i:! i:¡ l:1 o:0 s:$ s:5 b:8 t:7 c:(

# RECURSIVE LEET TRANSFORMS - Enables a recursive call to leet_transforms() function
# Comment this line or set it to false in case you don't want to get all possible leet transforms
# (!) Warning: enabled with huge --max parameters (e.g.: greater than 18) could take several minutes
recursive_leet=true

[LYRICS]
# Remove all parenthesis in lyrics found before any transform
remove_parenthesis=true
# Produce words based on initial of each word in phrases found
# (if enabled with remove_parenthesis disabled, it can produce useless words)
take_initials=true
artist_split_by_word=true
artist_space_replacement=true
lyric_split_by_word=false
lyric_space_replacement=true
# SPACE REPLACEMENT CHARSET - Characters and/or strings to insert instead of spaces
# inside an artist name or a lyric phrase
# Comment two above lines or set it empty in order to don't replace spaces, just remove them
space_replacement_chars=!@+._-
space_replacement_strings=
# Uncomment the following line to get an extensive charset
space_replacement_chars=!"#$%%&'()*+,-./:;<=>?@[\]^_`{|}~
```


- I am using the interactive mode. One of the words passed in the other relevant words field contains a `'`. _I don't know whether that is causing the issue_. The words passed in this field are all in lowercase and have been separated with commas as instructed.

**Comment by r3nt0n** [comment] 2023-02-11 17:03
Ok, now I see the issue, the error is generated by having two lines with the same key uncommented (i.e. you need to comment the basic charset in addition to uncomment the extensive one). The docs didn't help, since it didn't make this point clear at all, so I have updated it in the last commit (#23). I will close the issue, please let me know if it solved your problem.

Regarding the quote marks, it shouldn't be an issue on interactive mode. The only special thing to keep in mind about that: when using the non-interactive mode, if you want to provide words with single or double quote marks within your args, escape it with backslashes, .e.g.: `bopscrk -w John,O\'hara,Doe,foo,bar`. I also included this info in the docs with the last commit.

Thank you for your contribution!

**Closed by r3nt0n** 2023-02-11 17:03 UTC
Labels: good first issue

**Comment by pronoym99** [comment] 2023-02-11 17:31
Thanks!! It is working now.
